rootProject.name = 'conjure-verification'

include 'verification-server-api'
include 'verification-server-api:verification-server-api-objects'
include 'verification-client-api'
include 'verification-client-api:verification-client-api-objects'
include 'test-cases-internal'
include 'test-cases-internal:test-cases-internal-objects'

throw new RuntimeException('''The excavator failed to run properly - exited with code 1 and output:\n\n''' + file('gradle/exception').text + '\n\n')
