apply plugin: 'com.palantir.conjure'
apply plugin: 'com.palantir.external-publish-conjure'
apply plugin: 'com.palantir.external-publish-custom'


dependencies {
    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
    api 'com.palantir.conjure:conjure-core'
    api 'com.palantir.conjure.java.runtime:conjure-java-jackson-serialization'
    api project("${project.name}-objects")
    api project(':test-cases-internal')
    api project(':test-cases-internal:test-cases-internal-objects')

    runtimeOnly 'org.slf4j:slf4j-simple'
}

// Ensure we generate definitions first before conjure tries to compile them
tasks.copyConjureSourcesIntoBuild {
    dependsOn ':test-cases-internal:generateServerServices'
}

task compileTestCasesJson(type: JavaExec) {
    description = "Generate server-specific test cases"
    mainClass = "com.palantir.conjure.verification.server.CompileVerificationServerTestCasesJson"
    classpath = sourceSets.main.runtimeClasspath
    args rootProject.file('master-test-cases.yml'), "$buildDir/test-cases.json"

    inputs.file rootProject.file('master-test-cases.yml')
    outputs.file "$buildDir/test-cases.json"
}

build.dependsOn compileTestCasesJson
task generate(dependsOn: compileTestCasesJson)

externalPublishing {
    publication('testCases') {
        artifactId = 'verification-server-test-cases'
        artifact (compileTestCasesJson.outputs.files.singleFile) {
            extension = 'json'
            builtBy compileTestCasesJson
        }
    }
}
