[package]
name = "conjure-verification-server"
edition = "2021"
version = "0.1.0"
authors = ["Dan Sanduleac <dsanduleac@palantir.com>"]
license-file = "../LICENSE"

[dependencies]
conjure-verification-common = { path = "../verification-common" }
conjure-verification-http = { path = "../verification-http" }
conjure-verification-http-server = { path = "../verification-http-server" }
conjure-verification-error = { path = "../verification-error" }
conjure-verification-error-derive = { path = "../verification-error-derive" }
serde-conjure = { path = "../serde-conjure" }
serde-conjure-derive = { path = "../serde-conjure-derive" }

bytes = "1"
derive_more = { version = "1", features = ["from", "display"] }
either = "1.5"
http = "1"
hyper = { version = "1", features = ["server", "http1"] }
itertools = "0.14"
log = "0.4"
mime = "0.3"
pretty_env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_plain = "0.3"
