[package]
name = "conjure-verification-http-client-config"
edition = "2021"
version = "0.10.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
humantime-serde = "1"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
