[package]
name = "conjure-verification-common"
edition = "2021"
version = "0.1.0"
authors = ["Dan Sanduleac <dsanduleac@palantir.com>"]
license-file = "../LICENSE"

[dependencies]
conjure-verification-error = { path = "../verification-error" }
conjure-verification-error-derive = { path = "../verification-error-derive" }
serde-conjure = { path = "../serde-conjure" }
serde-conjure-derive = { path = "../serde-conjure-derive" }

base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
derive_more = { version = "1", features = ["from", "display"] }
derive-new = "0.7"
either = "1.5"
itertools = "0.14"
serde = "1.0"
serde-value = "0.5.2"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml_ng = "0.10"
serde_plain = "0.3"
uuid = { version = "1", features = ["v4", "serde"] }
